### ISSUE TITLE
When creating a new user in a Data Hub the Allow Access button is not working

### ISSUE THREAD

**Issue by HugoFelgueirasCF** [CorefluxCommunity/Coreflux-hub#5]
### Describe the bug 🐞

I wanted to create a new user with Access to the user configuration.

![Issue3](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/29081c25-f690-4dbe-98cb-7cd4814baee7)

The user was created but without the correct permissions even if the Allow Access button was selected. Then I went to the Users configuration option and selected the "Allow" for that user and it updated tp the correct status

 
![Issue4](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/50954c58-052a-415b-a56c-903c21aae9cc)

Now it's ok.

![Issue5](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/7ae17066-6d46-4eda-9ba0-de569b9c3e81)

### Steps to Reproduce 🔄

1. Create a new user with Allow access
2. Check the status in Mqtt Explorer
3. Change the status in the User Access Configuration 

### Expected behavior ✅

When creating a new user, if the option Allow Access is selected then that user is created with access to the root configuration

### Environment 🌐

Windows 11

### Terms of Service

- [X] I agree

**Comment by Jogana3** [comment]
Hi Hugo, this will be fixed in version 1.2.006
![image](https://github.com/CorefluxCommunity/Coreflux-hub/assets/64289121/e550d3a6-3481-4769-812b-f3c97ab05c07)
![image](https://github.com/CorefluxCommunity/Coreflux-hub/assets/64289121/6be534ad-b4d0-4158-8d53-f3f482370d7d)
![image](https://github.com/CorefluxCommunity/Coreflux-hub/assets/64289121/5d07cfd9-5d70-4b0d-b5ab-1df19b6dcab0)
